import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage();
await p.goto('http://localhost:4279/', { waitUntil: 'networkidle' });
await p.waitForFunction(() => window.__ct !== undefined, { timeout: 20000 });
await p.evaluate(() => window.__ct.clock(13,0)); await p.waitForTimeout(900);
await p.mouse.click(400, 250);
const hike = async (label, x, z, yaw, secs) => {
  await p.evaluate(([x,z,yaw]) => window.__ct.warp(x, z, yaw, 0.14, 0), [x,z,yaw]);
  await p.waitForTimeout(150);
  const a = await p.evaluate(() => window.__ct.pos());
  await p.keyboard.down('w'); await p.waitForTimeout(secs*1000); await p.keyboard.up('w');
  const c = await p.evaluate(() => window.__ct.pos());
  console.log(`  ${label}: ${Math.abs(c[2]-a[2]).toFixed(1)} m  (${a[2].toFixed(1)} -> ${c[2].toFixed(1)}) at x ${c[0].toFixed(2)}`);
};
console.log('walking THROUGH each 0.5 m collider (z -12.5, -44.2, -76.3):');
await hike('past z -44.2 northbound', 6.2, -47.0, Math.PI, 6);
await hike('past z -12.5 northbound', 6.2, -15.5, Math.PI, 6);
await hike('past z -76.3 southbound', 6.2, -73.5, 0, 6);
await b.close();
