#!/bin/sh
# Generate notes/STATUS.md — the one page Erick reads to see what is getting done.
#
# The user's words: *"i need more consistent updates and i want to know which
# things are getting done."* He cannot reprioritise a queue he cannot see, and
# until now the only view was LEDGER.md, which is 230+ rows of evidence prose.
#
# EVERYTHING HERE IS DERIVED. Nothing is hand-maintained, so it cannot go stale
# the way the queue checkboxes did (most were never ticked; see SESSION-STATE).
# Run it at every desk tick and commit the result.
set -u
cd "$(dirname "$0")/.." || exit 1
L=notes/LEDGER.md
OUT=notes/STATUS.md

# grep -c prints 0 AND EXITS 1 with no match, so assign plainly and default.
n_conf=$(grep -cE '^\| CONFIRMED \|' "$L"); n_conf=${n_conf:-0}
n_open=$(grep -cE '^\| OPEN \|' "$L");      n_open=${n_open:-0}
n_land=$(grep -cE '^\| LANDED \|' "$L");    n_land=${n_land:-0}
build=$(git rev-parse --short HEAD 2>/dev/null)
unpushed=$(git rev-list --count origin/add-stick-and-city98..add-stick-and-city98 2>/dev/null)

{
  echo "# What is getting done"
  echo
  echo "Generated by \`scripts/status.sh\` — do not hand-edit, it is overwritten."
  echo "Last run: $(date '+%Y-%m-%d %H:%M')  ·  build \`$build\`  ·  unpushed: ${unpushed:-?}"
  echo
  echo "**Play it:** http://localhost:5177/ (live, current) · https://erickfm.github.io/rpg/ (deployed)"
  echo
  echo "**$n_conf done · $n_open open · $n_land awaiting a check**"
  echo
  echo '---'
  echo
  echo "## Landed recently"
  echo
  git log --pretty='- **%ad** — %s' --date=format:'%b %d' -18 -- notes/LEDGER.md src \
    | sed 's/ — \(.\{96\}\).*/ — \1…/'
  echo
  echo '---'
  echo
  echo "## In flight right now"
  echo
  found=0
  for p in $(git worktree list 2>/dev/null | grep -o '/[^ ]*agent-[0-9a-f]*'); do
    b=$(git -C "$p" rev-parse --abbrev-ref HEAD 2>/dev/null)
    c=$(git rev-list --count add-stick-and-city98.."$b" 2>/dev/null)
    d=$(git -C "$p" status --porcelain 2>/dev/null | grep -vc node_modules)
    echo "- \`$(basename "$p")\` — ${c:-0} commits, ${d:-0} files touched"
    found=1
  done
  [ "$found" = 0 ] && echo "- nothing running; all slots free (cap is 5)"
  echo
  echo '---'
  echo
  echo "## Still open"
  echo
  echo "**Your asks** — things you said, not yet done:"
  echo
  grep -E '^\| OPEN \|' "$L" \
    | grep -viE '\| (AUDIT|desk) \|.*(verify|confirm|build SHAs|check suite|seampairs|D-outline|CONFIRMED rows)' \
    | awk -F'|' '{gsub(/^[ \t]+|[ \t]+$/,"",$3); gsub(/^[ \t]+|[ \t]+$/,"",$4);
                  printf "- **%s** — %s\n", $3, substr($4,1,108)}'
  echo
  echo "**Housekeeping** — my own bookkeeping and instrument faults, not your asks:"
  echo
  grep -E '^\| OPEN \|' "$L" \
    | grep -iE '\| (AUDIT|desk) \|.*(verify|confirm|build SHAs|check suite|seampairs|D-outline|CONFIRMED rows)' \
    | awk -F'|' '{gsub(/^[ \t]+|[ \t]+$/,"",$3); gsub(/^[ \t]+|[ \t]+$/,"",$4);
                  printf "- %s — %s\n", $3, substr($4,1,96)}'
  echo
  echo '---'
  echo
  echo "## How to read this"
  echo
  echo "- **A row is only \`done\` when someone walked it or looked at it**, not when"
  echo "  a builder said so. GOTCHAS 49: a row can be CONFIRMED and untrue."
  echo "- **A rising open count is usually the instrument improving**, not the world"
  echo "  getting worse. The sweep went from photographing 1 of 12 rooms to 12 of 12"
  echo "  on 2026-07-31 and immediately found four defects nobody could see before."
  echo "- **Queue checkboxes in \`notes/queues/\` are NOT maintained** and never were."
  echo "  This file and \`LEDGER.md\` are the truth."
} > "$OUT"

echo "wrote $OUT — $n_conf done, $n_open open"
