import { chromium } from 'playwright';
import { goto } from './lib/reachable.mjs';
const URL = process.env.SHOT_URL ?? 'http://localhost:4184/';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 900, height: 500 } });
await goto(page, URL);
await page.waitForFunction(() => window.__ct !== undefined, { timeout: 20000 });
const r = await page.evaluate(() => window.__ct.roomDims());
console.log(JSON.stringify(r, null, 2));
await browser.close();
