import { chromium } from 'playwright';
import { setClock } from '../lib/clock.mjs';
import { afterFrames } from '../lib/frames.mjs';
const b=await chromium.launch(); const p=await b.newPage({viewport:{width:1280,height:720}});
await p.goto(process.env.SHOT_URL||'http://localhost:4184/',{waitUntil:'networkidle'});
await p.waitForFunction(()=>window.__ct!==undefined,{timeout:15000});
await p.evaluate(()=>window.__ct.warp(916.5,-2,0,0,0)); await afterFrames(p,10); await p.waitForTimeout(2000);
await setClock(p,13);
await p.evaluate(()=>window.__ct.warp(916.5,-1.5,Math.PI,undefined,-0.02));
await afterFrames(p,6); await p.screenshot({path:'shots/lb3.png'});
const pos=await p.evaluate(()=>window.__ct.pos());
console.log(`  lb3.png from (${pos[0].toFixed(1)}, ${pos[2].toFixed(1)}) looking +z`);
await b.close();
